### ISSUE TITLE
MySQL credentials in for grammm-dbconf not read correctly

### ISSUE THREAD

**Issue by Raven24** [grommunio/admin-api#1]
Hi,
I set up a test-installation from the latest appliance, using the setup wizard.
Now I tried to change some details using grammm web admin and grammm-dbconf.
It was able to save the config to database via web admin, but when I tried to read it again, I got an HTTP 500 error.
On the console using `grammm-dbconf get -vvv postfix main.cf` this was the response:
```
# grammm-dbconf get -vvv postfix main.cf
Opening 'mysql_adaptor.cfg'...
Failed. Trying '/etc/gromox/mysql_adaptor.cfg'
Could not connect to MySQL server.
```
I had a look at the source code of `grammm-dbconf` and noticed it tried to read the mysql settings in all uppercase, but apparently the setup created them in lower case and only username, password and database.
Once I changed the config file `/etc/gromox/mysql_adaptor.cfg` to use uppercase names and included "MYSQL_HOST" and "MYSQL_PORT" (even though it's only on localhost), I was able to use `grammm-dbconf` as intended.

I think making the utility read the variable names case-insensitive and providing the a fallback for localhost and port 3306 should fix this.

**Comment by juliaschroeder** [comment]
Sorry for the late reply.
You are right, the gromox configuration files are case insensitive and dbconf should conform to that.
Also, `localhost`:`3306` should be used as default values.
The issue was fixed in 2c904961b995db2c5864a9fcd39e7c261422da87.
