### ISSUE TITLE
typo: grommunio-admin-exmdb(1)

### ISSUE THREAD

**Issue by crpb** [grommunio/admin-api#13]
Hi,

shouldn't that be `(0x2 for domains, 0x9 for users)`?

https://github.com/grommunio/admin-api/blob/2572d2c78a66117a86f7b017ecb84444db27e077/doc/man/grommunio-admin-exmdb.1#L153-L155

**Comment by juliaschroeder** [comment]
Yes, you are right. 
482afbb
