### ISSUE TITLE
exmdb folders: provide different output options

### ISSUE THREAD

**Issue by crpb** [grommunio/admin-api#5]
Hi,

would it be possible to either add an option to enable a *scripting-safe* output of the returned data? 
Or maybe even like the [**user**-module](https://github.com/grommunio/admin-api/blob/9b395f7f604b0dd3e78ec20aca9119cb9f2c47d3/cli/user.py#L326-L342) wth `--format [pretty|csv|json-flat|json-structured]`

Especially [those fancy chars](https://github.com/grommunio/admin-api/blob/bd1711406740586447d2bd5cf6e01fd048aebae1/cli/exmdb.py#L48-L50) can be bothersome.

I helped myself for now with stuff like `...| tr -d '└─├│'` , but in general it would be really awesome having the possibility to not even think about cleansing the returned data.
And i don't even wan't to know what type or characters could be problematic with for instance an cyrillic Charset.

cheers,
~crpb

**Comment by juliaschroeder** [comment]
Hey,

thanks for the feedback. Machine readable output shouldn't be too difficult.
I will add the option to generate folder lists in JSON format, probably both as tree and flat list.
If you have any other suggestions just let me know.

**Comment by grammmike** [comment]
included as per https://github.com/grommunio/admin-api/commit/1e03415dbb5984c8cda6ecea98195b86c43fc15c

see the format option, also documented here: https://docs.grommunio.com/man/grommunio-admin-exmdb.html
